### ISSUE TITLE
CamTest0.1.0.0  搭配 禾伸堂  FW TOF_20170419.bin 與 FW TOF_20170512.bin 兩個版本的 結果 :

### ISSUE THREAD

**Issue by Jones5829976** [lxnick/CamTest#2]
初步測試 了一下CamTest0.1.0.0  搭配 禾伸堂  FW TOF_20170419.bin 與 FW TOF_20170512.bin 兩個版本的 結果 :
Depth PID 會重複出現兩個  , 

 2CAB
 2CAB

1.	FW TOF_20170419.bin 
Module Color   OK !
Color  Module  , 偶而OK! 偶而只剩 Color 畫面  , Depth 無畫面
Module Depth , 當機  , Depth 無畫面
Depth Color , OK !
Color  Depth , 當機  , Depth 無畫面
Depth Module , 只剩 Color 畫面  , Depth 無畫面

2.	FW TOF_20170512.bin
Module Color  , OK!
Color Module  , 偶而OK! 偶而只剩 Color 畫面  , Depth 無畫面
Module Depth , 當機  , Depth 無畫面
Depth Color , OK!
Color Depth ,當機  , Depth 無畫面
Depth Module , 只剩 Color 畫面  , Depth 無畫面

**Comment by lxnick** [comment]
When switching devices from Device List Zone, there were some conditions:
1. critical section for data exchange was not release, cause deadlock
2. threads stop timing was not in order
thus cause program hang-up.

**Comment by lxnick** [comment]
For condition 1, 
a miss-status break condition was found in the code, it is a bug.

For condition 2, 
the thread will be stopped in sequence by stopping the threads step by step.

The problem was fixed at 0.1.0.1
